### ISSUE TITLE
Regarding ROI coordinates

### ISSUE THREAD

**Issue by nguyenkhaithinh** [Emory-HITI/EMBED_Open_Data#5]
Dear EMBED open data team,

Thank you very much for creating this impressive dataset. I have one question regarding the ROI coordinates; in the https://github.com/Emory-HITI/EMBED_Open_Data/blob/main/Sample_Notebook.ipynb, it seems like the stored coordinates of ROIs of RIGHT images are already flipped in the .csv file. As in the sample code, I cannot find where the flip left-right transform is for the ROI coordinates if the image is RIGHT.  Could you please verify whether the ROI coordinates of RIGHT images are already flipped?

**Comment by 111678900** [comment]
Hello,Can you tell me how to use this dataset? I can't find the DICOM related files, only a CSV file.

**Comment by nguyenkhaithinh** [comment]
Hi, here is the website providing information to download this dataset
https://aws.amazon.com/marketplace/pp/prodview-unw4li5rkivs2#overview
You need to complete the "EMBED Dataset Access Request" form and wait for permission to download the dataset; please remember to read the LICENSE.
